FUNCTION(VTK_TCL_WRAP fn)

	FILE(COPY ${CMAKE_CURRENT_SOURCE_DIR}/${fn}.h DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
	
	ADD_CUSTOM_COMMAND(
		OUTPUT ${fn}_wrap.cxx
		COMMAND ${VTKTclWrap_EXECUTABLE} -o ${CMAKE_CURRENT_BINARY_DIR}/${fn}_wrap.cxx ${CMAKE_CURRENT_SOURCE_DIR}/${fn}.h
		DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${fn}.h
		)
ENDFUNCTION()

	
FUNCTION(VTK_TCL_WRAP_INIT)
	STRING(REPLACE ";" "\\n" ARGNLIST "${ARGN}")
	ADD_CUSTOM_COMMAND(
		OUTPUT vtkTCLModuleList.txt
		COMMAND echo "FullMonteVTKTCL ${ARGNLIST}" > vtkTCLModuleList.txt
		WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
		VERBATIM)


    ADD_CUSTOM_COMMAND(
		OUTPUT vtkTCLInit.cxx
		DEPENDS vtkTCLModuleList.txt
		COMMAND ${VTKTclWrap_INIT_EXECUTABLE} vtkTCLModuleList.txt vtkTCLInit.cxx
		WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
ENDFUNCTION()
